### ISSUE TITLE
Close All Tabs

### ISSUE THREAD

**Issue by broerse** [ermouth/couch-photon#11]
I catch myself closing all tabs when I enter Photon after a few days. So I like to propose a close all tabs feature? And perhaps from the about page a link to this GitHub repository.

**Comment by ermouth** [comment]
Martin, I‘ve made a little UI research and discovered no settled common scenario for closing all tabs keeping app active. However, the proposal is absolutely reasonable.

The action proposed is pretty rare and is not common scenario, so how do you think, should double click on logo for closing all tabs be a reasonable solution?

**Comment by broerse** [comment]
I would suggest an extra close button on the far right, but left of the 4 icons that are there. Double click on the logo would work for me but how do other users who want to do this discover this feature?

**Comment by ermouth** [comment]
Added both features, thanks Martin! 

As for discoverability, now red alert “15 tabs max” also has a text about double click on Photon logo. Hope that‘s enough, since alert appears exactly when the user wants all those tabs to fade away.

**Comment by broerse** [comment]
Thanks it is perfect. Have a nice Easter.
