### ISSUE TITLE
Can't click on delete when I select too many databases

### ISSUE THREAD

**Issue by popojargo** [ermouth/couch-photon#13]
When I attempt to delete over 100 databases(a lot of databases), the confirm dialog stack all the names but it overflow. I have to edit the form and add a scroll to be able to click the delete button.

**Comment by ermouth** [comment]
Good point, thanks. There are two general ways to fix it:

1. Totally remove the list from the modal if selection size exceeds predefined value
2. Add a scroll to the modal.

Which one you think fits better? 

Also, what is your particular scenario of deletion a lot of buckets in a turn? I never ever deleted a lot of buckets simultaneously, so I just wonder why anyone should do it to understand end user better.

**Comment by popojargo** [comment]
@ermouth The scroll solution is less user friendly IMO but it lets you validate all the database that are being deleted.

Removing them somehow makes the modal useless.

What if you show some of them (hard limit), and you add a `Show more` button that shows them with a scroll?

**Comment by popojargo** [comment]
My context:
I was doing some tests on CouchDB and had some databases that weren't not cleaned up.

**Comment by ermouth** [comment]
> Removing them somehow makes the modal useless

Well, I hope not completely useless, but less useful and much more risky ) However I got your point and it‘s reasonable. I‘ll improve UX after bit more thinking on how to make it compact and informative.

Thanks again for pointing out ) Btw, if you have features to suggest – please, feel free.
