### ISSUE TITLE
Possibility to massive delete documents returned by a design document

### ISSUE THREAD

**Issue by matteospreafico** [ermouth/couch-photon#14]
Hello,

loving photon but I think it's still missing a couple of important feature.

**1)** Possibility to massive delete documents returned by a design document

**2)** Possibility to do a search by text in every document of the database

Do you think it would be possible to add those 2 things in the future?

Thanks!

**Comment by ermouth** [comment]
Hi, I‘m very shy about someone‘s love in verbal form, prefer likes and stars )

As for features proposed:
1. Please explain what do you mean exactly in ‘returned by a ddoc’.
2. Full text search would be great, however do you have any suggestions how to make it in reasonable way?

**Comment by ermouth** [comment]
Closed for no response.
