### ISSUE TITLE
Enable anonymous use

### ISSUE THREAD

**Issue by ondra-novak** [ermouth/couch-photon#19]
Currently only **_admin** and **photon-app** roles are able to use photon. It is some kind of false security. I can limit users through couchdb's permissions.

Is there an option to enable anonymous use ? (disable check of the roles}

**Comment by ermouth** [comment]
)) https://github.com/ermouth/couch-photon#configuring-access

**Comment by ermouth** [comment]
> It is some kind of false security

It’s some kind of protection from nosey strangers, not more. I‘ll add explicit notice, that it is not a DB security mechanics, thanks.

**Comment by ermouth** [comment]
@ondra-novak BTW I **explicitly** asked not to make continuous replications from repo. Please turn it off.
