### ISSUE TITLE
Codemirror box opens with hight half a line too small

### ISSUE THREAD

**Issue by johs** [ermouth/couch-photon#2]
<img width="427" alt="screen shot 2017-09-15 at 15 22 44" src="https://user-images.githubusercontent.com/48370/30484246-1cfc8770-9a2a-11e7-974c-bd4b25a49955.png">

**Comment by ermouth** [comment]
Do you see this glitch _always_, or only first time you click the value?

**Comment by johs** [comment]
It does not change the second time or by toggling the elemen. If I inspect it it gets the full height. Could it be related to no of code lines? Seems to dissapear if LOC is >6

**Comment by ermouth** [comment]
Much more probably it‘s related to Retina nuances, CM calculates font metrics drawing font in nearly invisible div and counting its height/width. It causes strange behavior sometimes on Retina devices.

Also possible that browser substitutes external font with Courier while the font itself is being downloaded, and CM get Courier metrics.

I‘ll look into it. If it‘s about Courier metrics, it‘s pretty easy fixable, if about Retina – not sure it‘s fixable at all without intervening CM.

**Comment by johs** [comment]
Just in case this is another clue, the oneline HTML comes up ok, while the one with highlighted markup has the problem. 
<img width="577" alt="screen shot 2017-09-15 at 16 17 37" src="https://user-images.githubusercontent.com/48370/30486694-9cd61680-9a31-11e7-8acd-94e35f5addb6.png">

**Comment by ermouth** [comment]
I finally checked it on iMac with retina, can’t confirm. It might get fixed during the year passed, at least I’ve upgraded CodeMirror, so closing.
