### ISSUE TITLE
Feature request: mass delete in view

### ISSUE THREAD

**Issue by ondra-novak** [ermouth/couch-photon#21]
Rows returned by any view (when reduce is not active) can be edited and deleted by one by. However I would appreciate to have an checkbox on each row to perform mark and then mass erase of documents that generated each row.

I realize that there is little complication in the fact that some documents may be in the view by multiple times. So the feature should be smart enough to avoid trying to delete same document by multiple times.

**Comment by ondra-novak** [comment]
![image](https://user-images.githubusercontent.com/9439234/72150712-77758680-33a6-11ea-9a55-bbd65dc8e313.png)

**Comment by ermouth** [comment]
Good proposal, seems this is what the author of #14 meant. I’ll do this when have enough time – the task isn’t so simple – however thanks for the idea, it might be indeed useful.

**Comment by ermouth** [comment]
@ondra-novak plz let me know does it fit your expectations.
