### ISSUE TITLE
It doesn't start

### ISSUE THREAD

**Issue by calpirro** [ermouth/couch-photon#25]
Hi

when I call index.html in the Chrome Developers Console I get this:

content.js:63009 Refused to create a worker from 'blob:http://127.0.0.1:5984/cfcfb34a-ce8a-48b2-b190-a546a1a039a5' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

Could you help me please? I'm lost...

Thanks

**Comment by ermouth** [comment]
There is no file named `content.js` in Photon, you are trying to start something else, or you have interfering Chrome extension. 

Also what do you mean _exactly_ saying you start index.html in dev console?

**Comment by calpirro** [comment]
I think that error is not relevant, I get it in all Fauxton pages and it works fine.

When I call photon index.html I get a blank screen, I opened the Developers Console and saw this error, I thought it was a photon issue...

I tried in Mozilla Firefox and it works fine. I'll do some research in my Chrome configuration & AddOns.

Thanks and sorry...

**Comment by ermouth** [comment]
I‘d highly recommend to revisit your list of extensions, because Chrome is blocking an attempt to load external code, and that block is ok, because emitting foreign code into page is obviously extremely unsafe for DB administration tool.
