### ISSUE TITLE
View Function not listed in Combo Box

### ISSUE THREAD

**Issue by kieperb** [ermouth/couch-photon#28]
If there is an multi line comment above the view function, the view function will not be listed in the Combobox.
```javascript
/**
*/
function (doc) {
...
```

![2020-08-13_couch-photon_screen](https://user-images.githubusercontent.com/36973284/90116188-6c783f80-dd55-11ea-83fc-6c7141aa9f1b.jpg)

**Comment by ermouth** [comment]
Good catch, gonna fix asap. Thanks!
