### ISSUE TITLE
Tabs cached in browser?

### ISSUE THREAD

**Issue by johs** [ermouth/couch-photon#3]
I loaded the editor after changins databases on the Couchdb instance and it displayed the tabs from previous session (like to non-existing databases)
Are the tabs cahced in the browser?

**Comment by ermouth** [comment]
Yes, there is no reasonable way to restore Photon tabs on reload except memoizing them in local storage. List of app tabs is memoized when browser tab closes.

**Comment by johs** [comment]
ok:)
