### ISSUE TITLE
Access to node managment _node/_local/_nodes/

### ISSUE THREAD

**Issue by ondra-novak** [ermouth/couch-photon#31]
Hi

Node management looks like ordinary DB. You can extract database info

```
curl "http://admin:xxxxxx@localhost:5984/_node/_local/_nodes/"
```
```
{"db_name":"_nodes","engine":"couch_bt_engine","doc_count":4,"doc_del_count":4,"update_seq":14,"purge_seq":0,"compact_running":false,"sizes":{"active":4074,"external":80,"file":143613},"instance_start_time":"1605607255951942","disk_format_version":8,"committed_update_seq":14,"compacted_seq":0,"props":{},"uuid":"fff7f43efd20ba82cd037e3289147ea5"}
```

... or **_all_docs** is also available.

Can the photon have an option to access this database to configure nodes?

Shard managment would be helpfull as well, but it is "nice to have" feature.

Thank you

**Comment by ermouth** [comment]
I’ll look into it, but only in December, very busy now. Thanks for suggestion, as usual very meaningful!

**Comment by ermouth** [comment]
@ondra-novak I started studying this peculiar artifact. Is it anywhere documented? Discovered this feature is missing in 2.3.0, however is present in 3.0.0

**Comment by ondra-novak** [comment]
It seems that path http://localhost:5984/_node/_local is local shard, which acts as separate database (which replaces old version of administration port). I tried to put photon.couch there, the database is accessible, but photon doesn't start.

(just put photon.couch into root of /var/lib/couchdb and restart couchdb)

**Comment by ondra-novak** [comment]
❤👍
