### ISSUE TITLE
Use update=lazy to list content of view

### ISSUE THREAD

**Issue by ondra-novak** [ermouth/couch-photon#32]
Especially after the view's script is updated, and being regenerated, the UI is blocked until the view is regenerated. Alternatively the operation can end with an error 500 because couchdb was unable to complete the operation in reasonable time. 

Optimal solution would be to switch to lazy mode after a few seconds of waiting. This feature is very missing on the couchdb API but can be simulated by waiting for view several seconds, abort the connection and switch to lazy mode (with some proper indication on the panel)

Photon is great tool, much much better than fauxton, thank you for all improvements.

**Comment by ermouth** [comment]
The proposal is quite reasonable, however it’s hardly implemented without re-designing entire implementation of a tab busy state. For now it’s an overkill, sorry.

However, I suggest you edit design doc as a json, having tab with appropriate view also open. To reach related ddoc, click the ddoc name at the right side of k/v table header:

<img width="1022" alt="Снимок экрана 2020-12-04 в 0 36 42" src="https://user-images.githubusercontent.com/1540047/101091313-0bf16480-35c9-11eb-83eb-fe90867272a5.png">

Then edit appropriate view as native JS (you will need to expand all parent keys to desired map function):

<img width="1021" alt="Снимок экрана 2020-12-04 в 0 38 11" src="https://user-images.githubusercontent.com/1540047/101091463-3fcc8a00-35c9-11eb-81fd-3981e4a9b592.png">

Then save ddoc. 

Inactive tab with view updates in background in this case, it does not block ddoc editor. You will see view updating, its tab shows animated “I’m busy” indicator.

**Comment by ondra-novak** [comment]
Ok, i understand. 

Thank you
