### ISSUE TITLE
Request - show fields in _all_docs view

### ISSUE THREAD

**Issue by rdewolff** [ermouth/couch-photon#34]
Hi

Thanks for your work, this version is really helpful and I love it!
 
I was wondering if you could add more fields displayed in the `_all_docs` view. It would be helpful to locate a document faster when working with the data. What do you think?

![contact_and_Flipper__0_98_0_](https://user-images.githubusercontent.com/130704/127097091-8bba7f5b-049a-46e3-b30e-b859cec22903.png)

Maybe simply show all fields in the table. Or better, allow us to parameter what fields we want to save :)

Cheers!

**Comment by ermouth** [comment]
Thanks. 

You likely mean grid view similar to Fauxton. Table view is already in my roadmap for a long time, however decent implementation requires serious effort – so no promises. 

As I see it, tables should be copyable to allow pasting into Excel or smth, also each column should have a sort of dropdown to  select a field to show, and also there’s still an open question about how cells with non-scalar values should be displayed. Even for scalar values it’s not so obvious, ie should we show strings wrapped with `""` or should we strip quotes for better copy/paste to Excel.

All those features do not fit well into both current UI template and set of libs onboard, so please have patience.

**Comment by ermouth** [comment]
Added first iteration of grid view, “include docs” option is still underway. https://github.com/ermouth/couch-photon/commit/9ee0a968272f7c02227e66fdb64d6e44122fb266

Cheers )

**Comment by rdewolff** [comment]
Thanks for your answer and the work. Will give this a try 🙏
