### ISSUE TITLE
Date - show date in grid view

### ISSUE THREAD

**Issue by rdewolff** [ermouth/couch-photon#36]
It would be great to see the date in human readable format in the grid view.

![meet](https://user-images.githubusercontent.com/130704/131817072-b8df97a0-a56e-478e-a9cb-741ca220e482.png)

**Comment by ermouth** [comment]
Good idea, but generally there’s not enough space. Mb put it in a tooltip?

**Comment by rdewolff** [comment]
In this case there is some space as second line as the ID is displayed. Even on a very wide screen, the ID is displayed on 2 lines.

And seems like the ID is always displayed?

![Screenshot 2021-09-02 at 14 09 31](https://user-images.githubusercontent.com/130704/131841050-8f035512-79a3-4373-b113-3c532b310c4c.png)

**Comment by ermouth** [comment]
Btw you can change width limiting in Photon settings tab, it goes under `Max width` setting. Also key column width may eventually be more smart and adapt its width – that task is long in my backlog.

Anyway, I’ll think how to implement your idea. I’m pretty sure it won’t be plain visible label, however it may be sort of button aside each date, or tooltip, or some sort of modifiers for column heads (like `.doc.dateTo /date`), or numbers themselves may be just clickable which will rotate format (date/hex/whatever).

**Comment by ermouth** [comment]
@rdewolff since v1.15.15 you can add ` /cast` modifiers after value path. Ie `.doc.timestamp /dt` will convert stamps to dates and show dates. Available cast functions reveal themselves on typing ` /` in field selector.

Thanks for proposal.

**Comment by rdewolff** [comment]
Just tested this, amazing. Thanks for your work @ermouth 🥳
