### ISSUE TITLE
CouchDB 3.2.1 - Message "JavaScript is disabled which likely means CouchDB CSP policy prevents Photon from starting. ..."

### ISSUE THREAD

**Issue by francwalter** [ermouth/couch-photon#40]
Hallo
I updated couchdb from 2.3.1 to 3.2.1 (I had to update because of some conflicting dependencies) and now Photon is not working anymore.
I have only the message:

```
JavaScript is disabled which likely means CouchDB CSP policy prevents Photon from starting. To fix the policy:

    Right-click Fauxton link and select Open in new tab...
    Switch to Fauxton tab, click + Add option button
    Fill popup with csp, attachments_enable, and false values respectively, click Create button.

After tuning CSP you will need to shift-reload this tab (Ctrl-Shift-R). If Photon still fails to start close the tab, and then re-open it (Ctrl-W, then Ctrl-Shift-T)
Photon 1.19
```

I tried this but without success.
It is not very exact, the fix-howto, I have in "Add option" three entries: section, name and value:

![grafik](https://user-images.githubusercontent.com/927269/161434501-2b8562f3-9cc4-4968-961b-17ce0f399446.png)

so I tried to leave section empty and add two options but no change. Then I put as section csr and add one option, same.
Can it be that couchdb v3 has changed something here?

I uninstalled it and installed again with copy and paste (the photon.json), no change.

How can I get photon running? With CouchDB v2 it worked bestly.
Thanks
frank

**Comment by ermouth** [comment]
> Fill popup with csp, attachments_enable, and false values respectively

There are 3 input fields: `Section`, `Name` and `Value`. There are also 3 values `csp`, `attachments_enable` and `false`. You need to put all three.

> as section csr

Likely misspell, you need to write `csp`.

**Comment by francwalter** [comment]
OH, yeah, now it works :)
Thank!!!
It was indeed a misspell, but not "csp", I wrote "attechment_enable" (instead of attachments_enable), my bad ;)
Thank, you are quick and helpful 👍 
frank
