### ISSUE TITLE
CSS opinions:)

### ISSUE THREAD

**Issue by johs** [ermouth/couch-photon#5]
I am sure you have tweeked this very carefully, so use it for what it's worth
.my-manifest-1aoc1xfl .irow:hover {
    background-color: rgba(128, 171, 238, 0.08);
}
...looks better with me than rgba(128, 171, 238,0.04);
On my iMac retina with sunlight through the window of the room, I could not see the hover color in the JSON editor
<img width="342" alt="screen shot 2017-09-15 at 16 06 35" src="https://user-images.githubusercontent.com/48370/30486162-f0ddab14-9a2f-11e7-9f81-cb633d5304e6.png">

At the right end of each line you have these nice item buttons, and using a big screen it is helpful to connect them with a slighly darker tone. (not that I don't like your very soft coloring)

**Comment by ermouth** [comment]
It‘s known issue, one guy with PC notebook does not see strips at all, in PC world there exist TFTs that white-out everything 240+ o_O

Highlight intensity, as well as font size/weight, font families for code and UI, max width, browser tab icon, poll interval and several other params are planned to be configurable from UI.

It gonna be another section in About tab, it‘s underway. So wait for next week )

**Comment by ermouth** [comment]
Fixed.
