### ISSUE TITLE
User Manager

### ISSUE THREAD

**Issue by broerse** [ermouth/couch-photon#9]
I really like Photon and I would like to manage users direct from Photon like I do now with this tool.

http://gr2m.github.io/couchdb-user-management-app/

**Comment by ermouth** [comment]
Actually right now when you click ‘New doc...’ being in `_replicator` or `_users` bucket, newly created blank doc already has structure relevant for the bucket.

However, Photon definitely might have more features for users management. What I have plans to implement:
* smth like the tool you noticed above
* bulk user addition, from CSV presumably
* `empty-user.json` attach to _design/photon, which won‘t update with Photon and will hold default fields of `type:user` docs (so you may edit that json template and save back into Photon ddoc).

Thanks for your proposal!

**Comment by ermouth** [comment]
From 0.9.25 the ‘News doc’  button in `_users` bucket pops up dlg for quick user creation. Also if  DB list was accessed during session, the pop-up knows existing roles and shows future access rights to buckets.

First little step. Fo to About tab and click ‘Check updates’ )

**Comment by broerse** [comment]
Thanks! Will take a look tomorrow.

**Comment by broerse** [comment]
I like it very much. Enough steps for now. Thanks again.
